### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by robba82** [victorjonsson/Arlima#97]
Hi, got this message when I try to install Arlima:

Fatal error: Uncaught exception 'Exception' with message 'Table 'oneclick-1702.v5q1_arlima_articlelist_article' doesn't exist' in /home/u/u4922011/www/produkt/wp-content/plugins/Arlima-master/classes/WP/Facade.php:261 Stack trace: #0 /home/u/u4922011/www/produkt/wp-content/plugins/Arlima-master/classes/ListVersionRepository.php(590): Arlima_WP_Facade->runSQLQuery('SELECT * FROM v...') #1 /home/u/u4922011/www/produkt/wp-content/plugins/Arlima-master/classes/WP/Plugin.php(581): Arlima_ListVersionRepository->updateDatabaseTables(0) #2 /home/u/u4922011/www/produkt/wp-content/plugins/Arlima-master/classes/WP/Plugin.php(277): Arlima_WP_Plugin::update() #3 [internal function]: Arlima_WP_Plugin->adminInitHook('') #4 /home/u/u4922011/www/produkt/wp-includes/plugin.php(496): call_user_func_array(Array, Array) #5 /home/u/u4922011/www/produkt/wp-settings.php(353): do_action('init') #6 /home/u/u4922011/www/produkt/wp-config.php(96): require_once('/home/u/u492201...') #7 /home/u/u4922011/www/produkt/wp-load.php(37): require_once('/home in /home/u/u4922011/www/produkt/wp-content/plugins/Arlima-master/classes/WP/Facade.php on line 261

What´s the problem?

Thanks!

**Comment by victorjonsson** [comment]
What wp-version is installed?

**Comment by robba82** [comment]
4.2.2

**Comment by robba82** [comment]
Beror det på att den senaste WP-versionen är installerad?

**Comment by victorjonsson** [comment]
I'm guessing that you have installed Arlima network-wide on a multi-site installation of wordpress. This is not supported https://github.com/victorjonsson/Arlima/issues/89#issuecomment-77328055

**Comment by mykebou** [comment]
I have problem with the installation because it's not showing the stylesheet
