### ISSUE TITLE
Error on activation

### ISSUE THREAD

**Issue by khromov** [victorjonsson/Arlima#98]
Using beta43, WP 4.3.1, single-site install.

```
[Tue Nov 10 21:04:46.394032 2015] [:error] [pid 4290] [client 2.248.121.43:56787] WordPress databasfel f\xc3\xb6r Table 'wptest.wp_arlima_articlelist_article' doesn't exist f\xc3\xb6rfr\xc3\xa5gan SELECT * FROM wp_arlima_articlelist_article LIMIT 0,1 skapat av require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), call_user_func_array, Arlima_WP_Plugin->adminInitHook, Arlima_WP_Plugin::update, Arlima_ListVersionRepository->updateDatabaseTables, Arlima_WP_Facade->runSQLQuery, QM_DB->query, referer: http://example.com/wptest/wp-admin/update.php?action=upload-plugin
[Tue Nov 10 21:04:46.394728 2015] [:error] [pid 4290] [client 2.248.121.43:56787] PHP Fatal error:  Uncaught exception 'Exception' with message 'Table 'wptest.wp_arlima_articlelist_article' doesn't exist' in /var/www/html/wptest/wp-content/plugins/Arlima-3.1.beta.43/classes/WP/Facade.php:311\nStack trace:\n#0 /var/www/html/wptest/wp-content/plugins/Arlima-3.1.beta.43/classes/ListVersionRepository.php(590): Arlima_WP_Facade->runSQLQuery('SELECT * FROM w...')\n#1 /var/www/html/wptest/wp-content/plugins/Arlima-3.1.beta.43/classes/WP/Plugin.php(499): Arlima_ListVersionRepository->updateDatabaseTables(0)\n#2 /var/www/html/wptest/wp-content/plugins/Arlima-3.1.beta.43/classes/WP/Plugin.php(268): Arlima_WP_Plugin::update()\n#3 [internal function]: Arlima_WP_Plugin->adminInitHook('')\n#4 /var/www/html/wptest/wp-includes/plugin.php(503): call_user_func_array(Array, Array)\n#5 /var/www/html/wptest/wp-settings.php(353): do_action('init')\n#6 /var/www/html/wptest/wp-config.php(89): require_once('/var/www/html/w...')\n#7 /var/www/html/wptest/wp-load.php(37): require_once('/var/www/html/w...')\n#8 /var/www/html/wptest/wp-admin/admi in /var/www/html/wptest/wp-content/plugins/Arlima-3.1.beta.43/classes/WP/Facade.php on line 311, referer: http://example.com/wptest/wp-admin/update.php?action=upload-plugin
[Tue Nov 10 21:04:57.139046 2015] [:error] [pid 4474] [client 2.248.121.43:56789] WordPress databasfel f\xc3\xb6r Table 'wptest.wp_arlima_articlelist_article' doesn't exist f\xc3\xb6rfr\xc3\xa5gan SELECT * FROM wp_arlima_articlelist_article LIMIT 0,1 skapat av require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), call_user_func_array, Arlima_WP_Plugin->adminInitHook, Arlima_WP_Plugin::update, Arlima_ListVersionRepository->updateDatabaseTables, Arlima_WP_Facade->runSQLQuery, QM_DB->query, referer: http://example.com/wptest/wp-admin/plugin-install.php?tab=commercial
[Tue Nov 10 21:04:57.139521 2015] [:error] [pid 4474] [client 2.248.121.43:56789] PHP Fatal error:  Uncaught exception 'Exception' with message 'Table 'wptest.wp_arlima_articlelist_article' doesn't exist' in /var/www/html/wptest/wp-content/plugins/Arlima-3.1.beta.43/classes/WP/Facade.php:311\nStack trace:\n#0 /var/www/html/wptest/wp-content/plugins/Arlima-3.1.beta.43/classes/ListVersionRepository.php(590): Arlima_WP_Facade->runSQLQuery('SELECT * FROM w...')\n#1 /var/www/html/wptest/wp-content/plugins/Arlima-3.1.beta.43/classes/WP/Plugin.php(499): Arlima_ListVersionRepository->updateDatabaseTables(0)\n#2 /var/www/html/wptest/wp-content/plugins/Arlima-3.1.beta.43/classes/WP/Plugin.php(268): Arlima_WP_Plugin::update()\n#3 [internal function]: Arlima_WP_Plugin->adminInitHook('')\n#4 /var/www/html/wptest/wp-includes/plugin.php(503): call_user_func_array(Array, Array)\n#5 /var/www/html/wptest/wp-settings.php(353): do_action('init')\n#6 /var/www/html/wptest/wp-config.php(89): require_once('/var/www/html/w...')\n#7 /var/www/html/wptest/wp-load.php(37): require_once('/var/www/html/w...')\n#8 /var/www/html/wptest/wp-admin/admi in /var/www/html/wptest/wp-content/plugins/Arlima-3.1.beta.43/classes/WP/Facade.php on line 311, referer: http://example.com/wptest/wp-admin/plugin-install.php?tab=commercial
```

**Comment by chredd** [comment]
@victorjonsson Do you know if this is a known issue?
